---
name: Test-Harness
version: 3.17_02

author:
  - 'Andy Armstrong  C<< <andy@hexten.net> >>'
abstract: Run Perl standard test scripts with statistics
license: perl
resources:
  MailingList: 'mailto:<tapx-dev@hexten.net>'
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-Harness
  homepage: http://testanything.org/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/AndyA/Test-Harness/tree/master
recommends:
  Pod::Usage: 1.12
configure_requires:
  Module::Build: 0.35
provides:
  App::Prove:
    file: lib/App/Prove.pm
    version: 3.17_01
  App::Prove::State:
    file: lib/App/Prove/State.pm
    version: 3.17_01
  App::Prove::State::Result:
    file: lib/App/Prove/State/Result.pm
    version: 3.17_01
  App::Prove::State::Result::Test:
    file: lib/App/Prove/State/Result/Test.pm
    version: 3.17_01
  TAP::Base:
    file: lib/TAP/Base.pm
    version: 3.17_01
  TAP::Formatter::Base:
    file: lib/TAP/Formatter/Base.pm
    version: 3.17_01
  TAP::Formatter::Color:
    file: lib/TAP/Formatter/Color.pm
    version: 3.17_01
  TAP::Formatter::Console:
    file: lib/TAP/Formatter/Console.pm
    version: 3.17_01
  TAP::Formatter::Console::ParallelSession:
    file: lib/TAP/Formatter/Console/ParallelSession.pm
    version: 3.17_01
  TAP::Formatter::Console::Session:
    file: lib/TAP/Formatter/Console/Session.pm
    version: 3.17_01
  TAP::Formatter::File:
    file: lib/TAP/Formatter/File.pm
    version: 3.17_01
  TAP::Formatter::File::Session:
    file: lib/TAP/Formatter/File/Session.pm
    version: 3.17_01
  TAP::Formatter::Session:
    file: lib/TAP/Formatter/Session.pm
    version: 3.17_01
  TAP::Harness:
    file: lib/TAP/Harness.pm
    version: 3.17_01
  TAP::Object:
    file: lib/TAP/Object.pm
    version: 3.17_01
  TAP::Parser:
    file: lib/TAP/Parser.pm
    version: 3.17_01
  TAP::Parser::Aggregator:
    file: lib/TAP/Parser/Aggregator.pm
    version: 3.17_01
  TAP::Parser::Grammar:
    file: lib/TAP/Parser/Grammar.pm
    version: 3.17_01
  TAP::Parser::Iterator:
    file: lib/TAP/Parser/Iterator.pm
    version: 3.17_01
  TAP::Parser::Iterator::Array:
    file: lib/TAP/Parser/Iterator/Array.pm
    version: 3.17_01
  TAP::Parser::Iterator::Process:
    file: lib/TAP/Parser/Iterator/Process.pm
    version: 3.17_01
  TAP::Parser::Iterator::Stream:
    file: lib/TAP/Parser/Iterator/Stream.pm
    version: 3.17_01
  TAP::Parser::IteratorFactory:
    file: lib/TAP/Parser/IteratorFactory.pm
    version: 3.17_01
  TAP::Parser::Multiplexer:
    file: lib/TAP/Parser/Multiplexer.pm
    version: 3.17_01
  TAP::Parser::Result:
    file: lib/TAP/Parser/Result.pm
    version: 3.17_01
  TAP::Parser::Result::Bailout:
    file: lib/TAP/Parser/Result/Bailout.pm
    version: 3.17_01
  TAP::Parser::Result::Comment:
    file: lib/TAP/Parser/Result/Comment.pm
    version: 3.17_01
  TAP::Parser::Result::Plan:
    file: lib/TAP/Parser/Result/Plan.pm
    version: 3.17_01
  TAP::Parser::Result::Pragma:
    file: lib/TAP/Parser/Result/Pragma.pm
    version: 3.17_01
  TAP::Parser::Result::Test:
    file: lib/TAP/Parser/Result/Test.pm
    version: 3.17_01
  TAP::Parser::Result::Unknown:
    file: lib/TAP/Parser/Result/Unknown.pm
    version: 3.17_01
  TAP::Parser::Result::Version:
    file: lib/TAP/Parser/Result/Version.pm
    version: 3.17_01
  TAP::Parser::Result::YAML:
    file: lib/TAP/Parser/Result/YAML.pm
    version: 3.17_01
  TAP::Parser::ResultFactory:
    file: lib/TAP/Parser/ResultFactory.pm
    version: 3.17_01
  TAP::Parser::Scheduler:
    file: lib/TAP/Parser/Scheduler.pm
    version: 3.17_01
  TAP::Parser::Scheduler::Job:
    file: lib/TAP/Parser/Scheduler/Job.pm
    version: 3.17_01
  TAP::Parser::Scheduler::Spinner:
    file: lib/TAP/Parser/Scheduler/Spinner.pm
    version: 3.17_01
  TAP::Parser::Source:
    file: lib/TAP/Parser/Source.pm
    version: 3.17_01
  TAP::Parser::SourceHandler:
    file: lib/TAP/Parser/SourceHandler.pm
    version: 3.17_01
  TAP::Parser::SourceHandler::Executable:
    file: lib/TAP/Parser/SourceHandler/Executable.pm
    version: 3.17_01
  TAP::Parser::SourceHandler::File:
    file: lib/TAP/Parser/SourceHandler/File.pm
    version: 3.17_01
  TAP::Parser::SourceHandler::Handle:
    file: lib/TAP/Parser/SourceHandler/Handle.pm
    version: 3.17_01
  TAP::Parser::SourceHandler::Perl:
    file: lib/TAP/Parser/SourceHandler/Perl.pm
    version: 3.17_01
  TAP::Parser::SourceHandler::RawTAP:
    file: lib/TAP/Parser/SourceHandler/RawTAP.pm
    version: 3.17_01
  TAP::Parser::SourceHandler::pgTAP:
    file: lib/TAP/Parser/SourceHandler/pgTAP.pm
    version: 3.17_01
  TAP::Parser::Utils:
    file: lib/TAP/Parser/Utils.pm
    version: 3.17_01
  TAP::Parser::YAMLish::Reader:
    file: lib/TAP/Parser/YAMLish/Reader.pm
    version: 3.17_01
  TAP::Parser::YAMLish::Writer:
    file: lib/TAP/Parser/YAMLish/Writer.pm
    version: 3.17_01
  Test::Harness:
    file: lib/Test/Harness.pm
    version: 3.17_01
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - TAP
  - test harness
  - prove
