---
name: TAP-Parser
version: 0.50_07
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: Parse L<TAP|Test::Harness::TAP> output
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Pod::Usage: 0
  Test::More: 0
provides:
  TAP::Base:
    file: lib/TAP/Base.pm
    version: 0.50_07
  TAP::Harness:
    file: lib/TAP/Harness.pm
    version: 0.50_07
  TAP::Harness::Color:
    file: lib/TAP/Harness/Color.pm
    version: 0.50_07
  TAP::Harness::Compatible:
    file: lib/TAP/Harness/Compatible.pm
    version: 0.50_07
  TAP::Harness::Compatible::Iterator:
    file: lib/TAP/Harness/Compatible/Iterator.pm
    version: 0.50_07
  TAP::Harness::Compatible::Point:
    file: lib/TAP/Harness/Compatible/Point.pm
    version: 0.50_07
  TAP::Harness::Compatible::Results:
    file: lib/TAP/Harness/Compatible/Results.pm
    version: 0.50_07
  TAP::Harness::Compatible::Straps:
    file: lib/TAP/Harness/Compatible/Straps.pm
    version: 0.50_07
  TAP::Harness::Compatible::Util:
    file: lib/TAP/Harness/Compatible/Util.pm
    version: 0.50_07
  TAP::Parser:
    file: lib/TAP/Parser.pm
    version: 0.50_07
  TAP::Parser::Aggregator:
    file: lib/TAP/Parser/Aggregator.pm
    version: 0.50_07
  TAP::Parser::Grammar:
    file: lib/TAP/Parser/Grammar.pm
    version: 0.50_07
  TAP::Parser::Iterator:
    file: lib/TAP/Parser/Iterator.pm
    version: 0.50_07
  TAP::Parser::Iterator::ARRAY:
    file: lib/TAP/Parser/Iterator.pm
    version: 0.50_07
  TAP::Parser::Iterator::FH:
    file: lib/TAP/Parser/Iterator.pm
    version: 0.50_07
  TAP::Parser::Result:
    file: lib/TAP/Parser/Result.pm
    version: 0.50_07
  TAP::Parser::Result::Bailout:
    file: lib/TAP/Parser/Result/Bailout.pm
    version: 0.50_07
  TAP::Parser::Result::Comment:
    file: lib/TAP/Parser/Result/Comment.pm
    version: 0.50_07
  TAP::Parser::Result::Plan:
    file: lib/TAP/Parser/Result/Plan.pm
    version: 0.50_07
  TAP::Parser::Result::Test:
    file: lib/TAP/Parser/Result/Test.pm
    version: 0.50_07
  TAP::Parser::Result::Unknown:
    file: lib/TAP/Parser/Result/Unknown.pm
    version: 0.50_07
  TAP::Parser::Source:
    file: lib/TAP/Parser/Source.pm
    version: 0.50_07
  TAP::Parser::Source::Perl:
    file: lib/TAP/Parser/Source/Perl.pm
    version: 0.50_07
  TAP::Parser::YAML:
    file: lib/TAP/Parser/YAML.pm
    version: 0.50_07
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
