---
name: Test-Harness
version: 3.03

author:
  - 'Andy Armstrong  C<< <andy@hexten.net> >>'
abstract: Run Perl standard test scripts with statistics
license: perl
resources:
  MailingList: 'mailto:<tapx-dev@hexten.net>'
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-Harness
  homepage: http://testanything.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.hexten.net/tapx/trunk
requires:
  File::Spec: 0.8
recommends:
  Pod::Usage: 1.12
provides:
  App::Prove:
    file: lib/App/Prove.pm
    version: 3.03

  TAP::Base:
    file: lib/TAP/Base.pm
    version: 3.03

  TAP::Formatter::Color:
    file: lib/TAP/Formatter/Color.pm
    version: 3.03

  TAP::Formatter::Console:
    file: lib/TAP/Formatter/Console.pm
    version: 3.03

  TAP::Formatter::Console::ParallelSession:
    file: lib/TAP/Formatter/Console/ParallelSession.pm
    version: 3.03

  TAP::Formatter::Console::Session:
    file: lib/TAP/Formatter/Console/Session.pm
    version: 3.03

  TAP::Harness:
    file: lib/TAP/Harness.pm
    version: 3.03

  TAP::Parser:
    file: lib/TAP/Parser.pm
    version: 3.03

  TAP::Parser::Aggregator:
    file: lib/TAP/Parser/Aggregator.pm
    version: 3.03

  TAP::Parser::Grammar:
    file: lib/TAP/Parser/Grammar.pm
    version: 3.03

  TAP::Parser::Iterator:
    file: lib/TAP/Parser/Iterator.pm
    version: 3.03

  TAP::Parser::Iterator::Array:
    file: lib/TAP/Parser/Iterator/Array.pm
    version: 3.03

  TAP::Parser::Iterator::Process:
    file: lib/TAP/Parser/Iterator/Process.pm
    version: 3.03

  TAP::Parser::Iterator::Stream:
    file: lib/TAP/Parser/Iterator/Stream.pm
    version: 3.03

  TAP::Parser::Multiplexer:
    file: lib/TAP/Parser/Multiplexer.pm
    version: 3.03

  TAP::Parser::Result:
    file: lib/TAP/Parser/Result.pm
    version: 3.03

  TAP::Parser::Result::Bailout:
    file: lib/TAP/Parser/Result/Bailout.pm
    version: 3.03

  TAP::Parser::Result::Comment:
    file: lib/TAP/Parser/Result/Comment.pm
    version: 3.03

  TAP::Parser::Result::Plan:
    file: lib/TAP/Parser/Result/Plan.pm
    version: 3.03

  TAP::Parser::Result::Test:
    file: lib/TAP/Parser/Result/Test.pm
    version: 3.03

  TAP::Parser::Result::Unknown:
    file: lib/TAP/Parser/Result/Unknown.pm
    version: 3.03

  TAP::Parser::Result::Version:
    file: lib/TAP/Parser/Result/Version.pm
    version: 3.03

  TAP::Parser::Result::YAML:
    file: lib/TAP/Parser/Result/YAML.pm
    version: 3.03

  TAP::Parser::Source:
    file: lib/TAP/Parser/Source.pm
    version: 3.03

  TAP::Parser::Source::Perl:
    file: lib/TAP/Parser/Source/Perl.pm
    version: 3.03

  TAP::Parser::YAMLish::Reader:
    file: lib/TAP/Parser/YAMLish/Reader.pm
    version: 3.03

  TAP::Parser::YAMLish::Writer:
    file: lib/TAP/Parser/YAMLish/Writer.pm
    version: 3.03

  Test::Harness:
    file: lib/Test/Harness.pm
    version: 3.03

generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
keywords:
  - TAP
  - test harness
  - prove
